export class Questionaire {
  public ageCategory = -1;
  public residentialSituation = -1;
  public workingSituation = -1;
  public smokingSituation = -1;
  public traveled = -1;
  public heinsberg = -1;
  public backFromHeinsberg = '';
  public foreignCountries = -1;
  public contactToPositives = -1;
  public lastCcontactToPositives = '';
  public fever = -1;
  public shiver = -1;
  public defeated = -1;
  public achingLimbs = -1;
  public cough = -1;
  public snuff = -1;
  public diarrhoea = -1;
  public itemSoreThroat  = -1;
}
