version: '3.4'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:      
      - "8088:80"
      - "8089:443"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: 'mcr.microsoft.com/mssql/server:2017-latest'
    environment:
      MSSQL_SA_PASSWORD: 'Test12341234'
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
    ports: 
      - 1433:1433